apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: py-test-rv
  janus-idp.io/tekton: py-test-rv
  backstage.io/kubernetes-id: py-test-rv
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: py-test-rv
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
