apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: py-test-rv
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: py-test-rv 
  name: py-test-rv
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: py-test-rv 
