apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: py-test-rv-gitops
  description: This is GitOps manifest for py-test-rv   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=py-test-rv
    backstage.io/kubernetes-id: py-test-rv 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: py-test-rv   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:py-test-rv
