apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: py-test-rv
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.cluster-bzftl.bzftl.sandbox1231.opentlc.com/rhtap/raisa-test:2041d5213b815f0069005084002f818dbc814d8b@sha256:d132f3e35d46ec3a5d284ea75361beec6ea159369619c6ad197eb76c6f83af69
          name: container-image
